PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVI_GENCUSTIT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVI_GENCUSTIT-PURPOSE .
    FIELD ZVI_GENCUSTIT-ORG_LEVEL .
    FIELD ZVI_GENCUSTIT-KEY_VALUE .
    FIELD ZVI_GENCUSTIT-VALID_FROM .
    FIELD ZVI_GENCUSTIT-USERNAME .
    FIELD ZVI_GENCUSTIT-COUNTER .
    FIELD ZVI_GENCUSTIT-VALUE .
    FIELD ZVI_GENCUSTIT-INACTIVE .
    FIELD ZVI_GENCUSTIT-DESCRIPTION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVI_GENCUSTIT-PURPOSE .
    FIELD ZVI_GENCUSTIT-ORG_LEVEL .
    FIELD ZVI_GENCUSTIT-KEY_VALUE .
    FIELD ZVI_GENCUSTIT-VALID_FROM .
    FIELD ZVI_GENCUSTIT-USERNAME .
    FIELD ZVI_GENCUSTIT-COUNTER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
